"""empty message

Revision ID: 1262ab1f52bc
Revises: 2d1021054d00
Create Date: 2019-03-09 19:55:30.304381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1262ab1f52bc'
down_revision = '2d1021054d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('authorization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['Authorization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
