"""empty message

Revision ID: 2d1021054d00
Revises: acfd33f4b1a5
Create Date: 2019-03-09 18:34:30.960022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1021054d00'
down_revision = 'acfd33f4b1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authorization', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Authorization', 'created_at')
    # ### end Alembic commands ###
