"""empty message

Revision ID: 5ee7374df31e
Revises: c940c5eda9f7
Create Date: 2019-03-09 20:49:29.675414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee7374df31e'
down_revision = 'c940c5eda9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_authorization_id_fkey', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_authorization_id_fkey', 'user', 'authorization', ['authorization_id'], ['id'])
    # ### end Alembic commands ###
