"""empty message

Revision ID: 7da8c65901ea
Revises: 5ee7374df31e
Create Date: 2019-03-09 20:58:20.675802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da8c65901ea'
down_revision = '5ee7374df31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'country')
    op.drop_column('user', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
