"""empty message

Revision ID: 9ef2d8543633
Revises: 7da8c65901ea
Create Date: 2019-03-10 17:25:34.595742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef2d8543633'
down_revision = '7da8c65901ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('music', sa.String(), nullable=False),
    sa.Column('song_lyrics', sa.Text(), nullable=False),
    sa.Column('searched_artist', sa.String(), nullable=False),
    sa.Column('searched_music', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Music')
    # ### end Alembic commands ###
