"""empty message

Revision ID: bd5c6389caa6
Revises: 9ef2d8543633
Create Date: 2019-03-11 22:54:27.386542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5c6389caa6'
down_revision = '9ef2d8543633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Music', sa.Column('translate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Music', 'translate')
    # ### end Alembic commands ###
